name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  firebase_auth: ^5.1.3
  cloud_firestore: ^5.4.4
  provider: ^6.1.2
  file_picker: ^10.3.6
  google_fonts: ^6.3.2
  url_launcher: ^6.3.2
  firebase_storage: ^12.4.10   # upgrade only
  fl_chart: ^1.1.1
  supabase_flutter: ^1.9.0
  webview_flutter: ^4.2.1
  crypto: ^3.0.2
  http: ^1.0.0
  animations: ^2.0.6


  fluttertoast: ^8.2.6
  dtd: ^4.0.0
  flutter_lints: ^6.0.0
  json_rpc_2: ^4.0.0
  path: ^1.9.1
  stack_trace: ^1.12.1
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/ned_bg.jpg
    - assets/ned.jpg
    - assets/form.jpeg
    - assets/food1.jpg
    - assets/food4.jpg
    - assets/food5.jpg
    - assets/food2.jpg
    - assets/food3.jpg
